#!/bin/bash

source /etc/init.d/panic


function reset_panic() {
    # remove last panic details file
    rm -f ${PANIC_DETAILS_FILE}
    # reset panic counter 
    echo 0 > ${PANIC_COUNTER_FILE}
}

sleep 43200 && reset_panic
