#!/bin/bash

SWAP_FILE="/data/varlib/swapfile"
MIN_TOTAL_MEM=2  # GB


test -n "${OS_VERSION}" || source /etc/init.d/base


function enable_swap() {
    test -s ${SWAP_FILE} || return
    mkswap ${SWAP_FILE} &> /dev/null
    
    msg_begin "Enabling swap"
    swapon ${SWAP_FILE}
    test $? == 0 && msg_done || msg_fail
}


case "$1" in
    start)
        msg_begin "Checking available memory"
        installed_mem=$(cat /proc/meminfo | grep MemTotal | tr -s ' ' | cut -d ' ' -f 2)
        installed_mem=$((installed_mem / 1048576 + 1))  # GB
        test -s ${SWAP_FILE} && swap_mem=$(stat -c %s ${SWAP_FILE}) || swap_mem=0
        swap_mem=$((swap_mem / 1073741824))  # GB
        total_mem=$((installed_mem + swap_mem))

        if [[ ${total_mem} -ge ${MIN_TOTAL_MEM} ]]; then
            msg_done "${installed_mem}GB + ${swap_mem}GB"
            enable_swap
            exit 0
        fi
        
        required_swap_size=$((MIN_TOTAL_MEM - installed_mem))
        if [[ ${required_swap_size} -le 0 ]]; then
            msg_done  # should not happen
            enable_swap
            exit 0
        fi
        
        msg_done "${installed_mem}GB + ${swap_mem}GB (${required_swap_size}GB swap needed)"
        
        msg_begin "Allocating swap file"
        swapoff ${SWAP_FILE} &>/dev/null
        rm -f ${SWAP_FILE}
        dd if=/dev/zero of=${SWAP_FILE} bs=1G count=${required_swap_size} conv=fsync &> /dev/null
        if [[ $? == 0 ]]; then
            msg_done
        else
            msg_fail
            exit 0  # Continue booting without swap
        fi

        enable_swap
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

# Continue booting even if we failed to set up swap
exit 0
