#!/bin/bash

HW_CONF=/var/run/hardware.conf
USER_HW_CONF=/data/etc/hardware.conf

EXPANDER_GPIO=13
DEFAULT_LGW_RESET_GPIO=17
OG_LGW_RESET_GPIO=25
DEFAULT_ECC_ADDRESS=0x60
DEFAULT_ECC_SLOT=0

test -n "${OS_VERSION}" || source /etc/init.d/base


start() {
    msg_begin "Detecting hardware"

    # Enable GPIO expander that is present on OG and RAK models
    gpio.sh ${EXPANDER_GPIO} 1
    usleep 100000
    
    truncate -s0 ${HW_CONF}

    # Detect I2C peripherals
    HAS_EXPANDER=false
    HAS_GPS=false
    ECC_ADDRESS=${DEFAULT_ECC_ADDRESS}
    i2c_output=$(i2cdetect -y 1 | awk -F: '{print $2}')
    grep -q 20 <<< "${i2c_output}" && HAS_EXPANDER=true
    grep -q 42 <<< "${i2c_output}" && HAS_GPS=true
    grep -q 58 <<< "${i2c_output}" && ECC_ADDRESS=0x58
    grep -q 60 <<< "${i2c_output}" && ECC_ADDRESS=0x60

    LGW_RESET_GPIO=${DEFAULT_LGW_RESET_GPIO}
    if [[ ${HAS_GPS} == true ]]; then
        # OG models have GPS and use a different GPIO for reset
        LGW_RESET_GPIO=${OG_LGW_RESET_GPIO}
    fi
    
    HAS_LED_STRIP=false
    if grep -q Compute /proc/device-tree/model &>/dev/null; then
        # Assume all CM4-based units have LED strip
        HAS_LED_STRIP=true
    fi
    
    # Set the ECC slot number
    ECC_SLOT=${DEFAULT_ECC_SLOT}
    if [[ ${ECC_ADDRESS} == 0x58 ]]; then
        ECC_SLOT=2  # Some ECC models are on 0x58 and have slots 0 and 1 preprovisioned
    fi
    
    # User settings override detected ones
    test -s ${USER_HW_CONF} && source ${USER_HW_CONF}
    
    echo "HAS_GPS=${HAS_GPS}" >> ${HW_CONF}
    echo "ECC_ADDRESS=${ECC_ADDRESS}" >> ${HW_CONF}
    echo "ECC_SLOT=${ECC_SLOT}" >> ${HW_CONF}
    echo "HAS_EXPANDER=${HAS_EXPANDER}" >> ${HW_CONF}
    echo "HAS_LED_STRIP=${HAS_LED_STRIP}" >> ${HW_CONF}
    echo "LGW_RESET_GPIO=${LGW_RESET_GPIO}" >> ${HW_CONF}

    msg_done
}

case "$1" in
    start)
        start
        ;;

    stop)
        ;;
    
    *)
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac

exit $?
