#!/bin/bash

MKVPNPASSWD="/usr/libexec/mkvpnpasswd"
VPNPASSWD_FILE="/var/run/vpnpasswd"


test -n "${OS_VERSION}" || source /etc/init.d/base


start() {
    msg_begin "Generating VPN password"

    if ! [[ -e /dev/i2c-1 ]]; then
        msg_fail "no I2C device"
        return
    fi
    
    ${MKVPNPASSWD} > ${VPNPASSWD_FILE}

    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
