#!/bin/bash

MKVPNPASSWD="/usr/libexec/mkvpnpasswd"
VPNPASSWD_FILE="/var/run/vpnpasswd"
SYS_USER_SWARM_KEY="/usr/share/user_swarm_key"
BOOT_USER_SWARM_KEY="/boot/user_swarm_key"
USER_SWARM_KEY="/var/lib/user_swarm_key"


test -n "${OS_VERSION}" || source /etc/init.d/base

prepare_conf ${USER_SWARM_KEY} ${SYS_USER_SWARM_KEY} ${BOOT_USER_SWARM_KEY}


start() {
    msg_begin "Generating VPN password"

    if ! [[ -e /dev/i2c-1 ]] && ! [[ -s ${USER_SWARM_KEY} ]]; then
        msg_fail "no I2C device"
        return
    fi
    
    echo "${OS_PREFIX}-${BOARD_SN}" > ${VPNPASSWD_FILE}
    ${MKVPNPASSWD} ${USER_SWARM_KEY} 2>/var/log/mkvpnpasswd.log >> ${VPNPASSWD_FILE}

    if [[ $? == 0 ]]; then
        test -s ${USER_SWARM_KEY} && msg_done "with user swarm key" || msg_done "with ECC"
    else
        msg_fail
        rm -f ${VPNPASSWD_FILE}
    fi
}

case "$1" in
    start)
        start
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
