#!/bin/bash

MKVPNPASSWD="/usr/libexec/mkvpnpasswd"
VPNPASSWD_FILE="/var/run/vpnpasswd"


test -n "${OS_VERSION}" || source /etc/init.d/base


start() {
    msg_begin "Generating VPN password"

    if ! [[ -e /dev/i2c-1 ]]; then
        msg_fail "no I2C device"
        return
    fi
    
    echo "cham-${BOARD_SN}" > ${VPNPASSWD_FILE}
    ${MKVPNPASSWD} 2>/var/log/mkvpnpasswd.log >> ${VPNPASSWD_FILE}

    if [[ $? == 0 ]]; then
        msg_done
    else
        msg_fail
        rm -f ${VPNPASSWD_FILE}
    fi
}

case "$1" in
    start)
        start
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
