#!/bin/bash

SYS_CONF="/etc/openvpn"
BOOT_CONF="/boot/openvpn"
CONF="/data/etc/openvpn"

LOG="/var/log/openvpn.log"
PROG="/usr/sbin/openvpn"

NETWATCH_CONF="/etc/netwatch.conf"

REG_CONF="/var/lib/reg.conf"
VPNPASSWD_SCRIPT="/etc/init.d/S54vpnpasswd"
VPNPASSWD_MIN_INTERVAL=3600  # Seconds

KEEP_USER_CONF_FILE="${CONF}/keep_user_conf"


test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base

test -s ${REG_CONF} && source ${REG_CONF}

test -f ${KEEP_USER_CONF_FILE} || rm -rf ${CONF}  # Ignore any existing user config
prepare_conf ${CONF} ${SYS_CONF} ${BOOT_CONF}

source ${NETWATCH_CONF}

test -d ${CONF} || exit 0
test -s /var/run/vpnpasswd || exit 0


# Adjust the VPN server host according to region
REGION_PREFIX=${REGION_PREFIX:0:2}
REGION_PREFIX=${REGION_PREFIX:-us}
SERVER_HOST="et-${OS_PREFIX}-${REGION_PREFIX}.sbcloud.services"
sed -ri "s/remote.*1194/remote ${SERVER_HOST} 1194/" ${CONF}/client.conf


uptime_seconds() {
    cat /proc/uptime | grep -oE '^[[:digit:]]+'
}

running() {
    (killall -0 openvpn && ip link show tun0) &> /dev/null 
}

start_openvpn() {
    ${PROG} --config ${CONF}/client.conf --cd ${CONF} &>>/var/log/openvpn.log &
}

stop_openvpn() {
    killall $(basename ${PROG}) &>/dev/null
}

watch() {
    sleep ${NET_WATCH_DELAY}

    last_vpnpasswd_uptime=0
    dead_count=0
    while true; do
        sleep ${NET_WATCH_INTERVAL}
        if ! running; then
            logger -t openvpn "dead, restarting (count=${dead_count})"
            up=$(uptime_seconds)

            # Don't regenerate VPN password too often
            if [[ $((${up} - ${last_vpnpasswd_uptime})) -gt ${VPNPASSWD_MIN_INTERVAL} ]]; then
                ${VPNPASSWD_SCRIPT} start
                last_vpnpasswd_uptime=${up}
            fi

            stop_openvpn
            start_openvpn

            dead_count=$((dead_count + 1))
        else
            dead_count=0
        fi
    done
}

start() {
    msg_begin "Starting openvpn"
    modprobe tun
    
    start_openvpn
    test $? == 0 && msg_done || msg_fail
    
    if [[ "${LINK_WATCH}" == "true" ]]; then
        watch &
    fi
}

stop() {
    msg_begin "Stopping openvpn"
    stop_openvpn
    ps | grep $(basename ${PROG}) | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
    msg_done
}

case "$1" in
    start)
        start
        ;;
        
    stop)
        stop
        ;;
        
    restart)
        stop
        start
        ;;
    
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
