#!/bin/bash

SYS_CONF="/etc/openvpn"
BOOT_CONF="/boot/openvpn"
CONF="/data/etc/openvpn"

LOG="/var/log/openvpn.log"
PROG="/usr/sbin/openvpn"
PROG_ST="/sbin/sshtunnel"

WATCH_CONF="/data/etc/watch.conf"

LINK_WATCH=true
NETWATCH_RETRIES=3
NETWATCH_INTERVAL=20

REG_CONF="/var/lib/reg.conf"


test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base

test -s ${REG_CONF} && source ${REG_CONF}

rm -rf ${CONF}  # Ignore any existing user config
prepare_conf ${CONF} ${SYS_CONF} ${BOOT_CONF}

test -s ${WATCH_CONF} && source ${WATCH_CONF}
test -d ${CONF} || exit 0
test -s /var/run/vpnpasswd || exit 0


# Adjust the VPN server host according to region
SERVER_HOST="et.%ssyncrob.it"
SERVER_HOST=$(printf "${SERVER_HOST}" "${REGION_PREFIX}")
sed -ri "s/remote.*1194/remote ${SERVER_HOST} 1194/" ${CONF}/client.conf


running() {
    killall -0 openvpn &> /dev/null
}

watch() {
    tunnel_started=false
    while true; do
        sleep ${NETWATCH_INTERVAL}
        if ! running; then
            logger -t openvpn "dead, restarting"
            start_openvpn
            if [[ ${tunnel_started} == false ]]; then
                tunnel_started=true
                logger -t sshtunnel "starting"
                ${PROG_ST} start
            fi
        fi
    done
}

start_openvpn() {
    ${PROG} --config ${CONF}/client.conf --cd ${CONF} &>>/var/log/openvpn.log &
}

start() {
    msg_begin "Starting openvpn"
    modprobe tun
    
    start_openvpn
    test $? == 0 && msg_done || msg_fail
    
    if [[ "${LINK_WATCH}" == "true" ]]; then
        watch &
    fi
}

stop() {
    msg_begin "Stopping openvpn"
    killall $(basename ${PROG}) &>/dev/null
    ps | grep $(basename ${PROG}) | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
    msg_done
}

case "$1" in
    start)
        start
        ;;
        
    stop)
        stop
        ;;
        
    restart)
        stop
        start
        ;;
    
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
