#!/bin/bash

PROG="/usr/bin/cynogale"


test -n "${OS_VERSION}" || source /etc/init.d/base


start() {
    msg_begin "Starting cynogale"
    
    ${PROG} &

    test $? == 0 && msg_done || msg_fail
}

stop() {
    msg_begin "Stopping cynogale"
    
    base_prog=$(basename ${PROG})
    killall -q ${base_prog}
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
