#!/bin/bash

PROG="/opt/hotspot-api-server/main.py"
PYTHON="/usr/bin/python"
LOG="/var/log/hotspot-api-server.log"
CONF="/etc/hotspot-api-server.conf"
USER_CONF="/data/etc/hotspot-api-server.conf"

source /etc/init.d/base


start() {
    msg_begin "Starting hotspot API server"
    
    set -a
    source ${CONF}
    test -s ${USER_CONF} && source ${USER_CONF}
    set +a
    ${PYTHON} ${PROG} &>${LOG} &

    msg_done
}

stop() {
    msg_begin "Stopping hotspot API server"

    prog_name=$(basename ${PROG})
    ps | grep ${prog_name} | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
