#!/bin/bash

PROG="/opt/packet_forwarder/bin/lora_pkt_fwd"
CONF="/opt/packet_forwarder/etc/global_conf.json"
LOG="/var/log/packet_forwarder.log"


test -n "${OS_VERSION}" || source /etc/init.d/base


start() {
    msg_begin "Starting packet-forwarder"
    
    if ! [[ -e /dev/spidev0.0 ]]; then
        msg_fail "no SPI device"
        return
    fi
    
    cd $(dirname ${PROG})  # Must be run from the bin directory
    ${PROG} -c ${CONF} &>> ${LOG} &

    msg_done
}

stop() {
    msg_begin "Stopping packet-forwarder"
    
    base_prog=$(basename ${PROG})
    if killall -q ${base_prog}; then
        # Allow 2 seconds for a gracefulish shutdown
        sleep 2
        msg_done
    else
        msg_fail
    fi
    
    # Kill any remainings with SIGKILL
    ps | grep -E 'packet.?forwarder' | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill -9
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
