#!/bin/bash

test -n "${OS_VERSION}" || source /etc/init.d/base
test -e /var/log/provision.log || exit 0


start() {
    msg_begin "Provisioning cleanup"

    rm -f /var/log/provision.log
    rm -f /var/log/post-upgrade.log
    rm -rf /var/log/gateway_mfr
    
    msg_done
}

case "$1" in
    start)
        start
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
