#!/bin/bash

WORK_DIR="/opt/gateway_config"
PROG="bin/gateway_config"
FULL_PROG=${WORK_DIR}/${PROG}
LOG="/var/log/gateway_config/startup.log"
HCI_DIR="/sys/kernel/debug/bluetooth/hci0"
HARDWARE_CONF="/var/run/hardware.conf"


test -n "${OS_VERSION}" || source /etc/init.d/base

source ${HARDWARE_CONF}


setup_bluetooth() {
    connmanctl enable bluetooth &>/dev/null

    # Advertise on channels 37, 38 and 39
    echo 7 > ${HCI_DIR}/adv_channel_map

    # Send a beacon every 152.5 ms
    echo 153 > ${HCI_DIR}/adv_min_interval
    echo 153 > ${HCI_DIR}/adv_max_interval
    
    echo -e "pairable off\nquit" | timeout 1 /usr/bin/bluetoothctl &>/dev/null

    # Automatically enable pairing at boot
    (/bin/sleep 5 && HOME=/var/run ${FULL_PROG} advertise on) &>> ${LOG} &
}

start() {
    msg_begin "Starting gateway-config"
    
    if ! [[ -e ${HCI_DIR} ]]; then
        msg_fail "no bluetooth device"
        return
    fi
    
    mkdir -p $(dirname ${LOG})
    setup_bluetooth

    cd ${WORK_DIR}
    
    export DBUS_SESSION_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    export RUNNER_LOG_DIR="/var/log/gateway_config"
    export ERL_CRASH_DUMP="/var/log/gateway_config"
    export ERL_EPMD_ADDRESS="127.0.0.1"
    export ERL_FULLSWEEP_AFTER=0  # We don't care about performance, just don't eat up RAM
    export HOME=/var/run

    ${PROG} foreground &>> ${LOG} &

    msg_done
}

stop() {
    msg_begin "Stopping gateway-config"
    
    base_prog=$(basename ${PROG})
    if killall -q ${base_prog}; then
        # Allow 2 seconds for a gracefulish shutdown
        sleep 2
        msg_done
    else
        msg_fail
    fi
    
    # Kill any remainings with SIGKILL
    ps | grep -E 'gateway.?config' | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill -9
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
