#!/bin/bash

PROG="/opt/packet_forwarder/bin/lora_pkt_fwd"
PROG_M="/opt/miner/bin/miner"
CONF_TEMPLATE="/opt/packet_forwarder/etc/global_conf.json.sx1250.%s"
LOG="/var/log/packet_forwarder.log"
REG_TIMEOUT=300
DEF_REG="US915"


test -n "${OS_VERSION}" || source /etc/init.d/base


find_reg() {
    region=$(${PROG_M} info region 2>/dev/null)
    test $? == 0 || region=""

    # Can't detect region when provisioning, so we use a default instead of bailing out
    test -f /var/log/provision.log && test -z "${region}" && region=${DEF_REG}

    echo ${region}
}

start() {
    msg_begin "Starting packet-forwarder"
    
    if ! [[ -e /dev/spidev0.0 ]]; then
        msg_fail "no SPI device"
        return
    fi
    
    count=0
    while true; do
        reg=$(find_reg)
        if [[ -z "${reg}" ]]; then
            count=$((count + 1))
            if [[ ${count} -gt ${REG_TIMEOUT} ]]; then
                msg_fail "no regulatory information"
                logger -t packetforwarder "cannot start, calling panic action"
                panic_action packetforwarder
                return 1
            fi
            sleep 1
        else
            break
        fi
    done
    
    cd $(dirname ${PROG})  # Must be run from the bin directory
    conf=$(printf ${CONF_TEMPLATE} ${reg})
    ${PROG} -c ${conf} &>> ${LOG} &

    msg_done
}

stop() {
    msg_begin "Stopping packet-forwarder"
    
    base_prog=$(basename ${PROG})
    if killall -q ${base_prog}; then
        # Allow 2 seconds for a gracefulish shutdown
        sleep 2
        msg_done
    else
        msg_fail
    fi
    
    # Kill any remainings with SIGKILL
    ps | grep -E 'packet.?forwarder' | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill -9
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
