#!/bin/bash

PROG_TEMPLATE="/opt/packet_forwarder/bin/lora_pkt_fwd_%s"
PROG_M="/opt/miner/bin/miner"
PROG_CI="/opt/packet_forwarder/bin/chip_id"

JSON_CONF_TEMPLATE="/opt/packet_forwarder/etc/global_conf.json.%s.%s"
JSON_CONF="/var/run/global_conf.json"
USER_JSON_CONF="/data/etc/global_conf.json"

SYS_CONF="/etc/packet_forwarder.conf"
CONF="/data/etc/packet_forwarder.conf"

LOG="/var/log/packet_forwarder.log"
LIB_DIR="/opt/packet_forwarder/lib"

REG_TIMEOUT=7200
REG_CONF="/var/lib/reg.conf"
DEF_REG="US915"
MINER_READY_FILE="/var/run/miner_ready"

# TX power:      12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
SX1301_MIX_GAIN=( 9 15 10 10 11 12 13 14  9 10 10 10 10 11 12 14)
SX1301_PA_GAIN=(  2  1  2  2  2  2  2  2  3  3  3  3  3  3  3  3)
SX1301_DIG_GAIN=( 0  0  0  0  0  0  0  0  0  1  1  0  0  0  0  0)
SX1302_PWR_IDX=(  4  5  6  7  8  9 10 11 12 13 14 15 16 17 19 20)


declare -A SX1301_RSSI_OFFSET=( \
    [AS923]=-166.0 \
    [AS923_1]=-166.0 \
    [AS923_2]=-166.0 \
    [AS923_2]=-166.0 \
    [AU915]=-166.0 \
    [CN470]=-176.0 \
    [EU868]=-166.0 \
    [IN865]=-166.0 \
    [KR920]=-166.0 \
    [RU864]=-166.0 \
    [US915]=-166.0 \
)

declare -A SX1302_RSSI_OFFSET=( \
    [AS923]=-215.4 \
    [AS923_1]=-215.4 \
    [AS923_2]=-215.4 \
    [AS923_3]=-215.4 \
    [AU915]=-215.4 \
    [CN470]=-207.0 \
    [EU868]=-215.4 \
    [IN865]=-215.4 \
    [KR920]=-215.4 \
    [RU864]=-215.4 \
    [US915]=-215.4 \
)

declare -A DEF_TX_POWER=( \
    [AS923]=27 \
    [AS923_1]=27 \
    [AS923_2]=27 \
    [AS923_3]=27 \
    [AU915]=27 \
    [CN470]=27 \
    [EU868]=14 \
    [IN865]=27 \
    [KR920]=27 \
    [RU864]=27 \
    [US915]=27 \
)


test -n "${OS_VERSION}" || source /etc/init.d/base


find_reg() {
    region=$(${PROG_M} info region 2>/dev/null)
    test $? == 0 || region=""
    # Strip leading "region_" prefix
    if [[ "${region}" =~ ^region_ ]]; then
        region=${region:7}
    fi
    
    region=$(echo "${region}" | tr a-z A-Z)

    # Can't detect region when provisioning, so we use a default instead of bailing out
    test -f /var/log/provision.log && test -z "${region}" && region=${DEF_REG}

    echo ${region}
}

find_sx() {
    cd $(dirname ${PROG_CI})
    if ${PROG_CI} | grep -q "concentrator EUI:"; then
        echo "sx1302"
    else
        echo "sx1301"
    fi
}

prepare_conf_json() {
    # $1 - template
    # $2 - sx
    # $3 - reg
    
    template=$1
    sx=$2
    reg=$3

    export PF_ANTENNA_GAIN
    if [[ ${sx} == sx1301 ]]; then
        # TX power ranges from 12 to 27 dBm
        export PF_PA_GAIN=${SX1301_PA_GAIN[${PF_TX_POWER} - 12]}
        export PF_MIX_GAIN=${SX1301_MIX_GAIN[${PF_TX_POWER} - 12]}
        export PF_DIG_GAIN=${SX1301_DIG_GAIN[${PF_TX_POWER} - 12]}
        export PF_RSSI_OFFSET=$(echo "${PF_RSSI_OFFSET} + ${SX1301_RSSI_OFFSET[${reg}]}" | bc)
    else  # Assuming $2 == sx1302
        export PF_PWR_IDX=${SX1302_PWR_IDX[${PF_TX_POWER} - 12]}
        export PF_RSSI_OFFSET=$(echo "${PF_RSSI_OFFSET} + ${SX1302_RSSI_OFFSET[${reg}]}" | bc)
    fi
    cat ${template} | envsubst > ${JSON_CONF}
}

start() {
    msg_begin "Starting packet-forwarder"
    
    if ! [[ -e /dev/spidev0.0 ]]; then
        msg_fail "no SPI device"
        return
    fi
    
    count=0
    while true; do
        # Don't ask miner for region while syncing
        if ps aux | grep snapshot | grep -qv grep; then
            sleep 5
            continue
        fi

        reg=$(find_reg)
        if [[ -z "${reg}" ]]; then
            count=$((count + 60))
            if [[ ${count} -gt ${REG_TIMEOUT} ]]; then
                msg_fail "no region information"
                panic_action packetforwarder "no region information"
                return 1
            fi
            sleep 60
        else
            # At this point we know miner is ready
            touch ${MINER_READY_FILE} 
            break
        fi
    done
    
    # Remember the region for future use
    reg_prefix="$(echo ${reg} | cut -b1-2 | tr A-Z a-z)"
    echo "REGION=${reg}" > ${REG_CONF}
    echo "REGION_PREFIX=${reg_prefix}" >> ${REG_CONF}

    # User-editable configuration
    source ${SYS_CONF}  # Ensure defaults
    PF_TX_POWER=${DEF_TX_POWER[${reg}]}
    test -s ${CONF} && source ${CONF}

    sx=$(find_sx)
    if [[ -n "${PF_PROG}" ]]; then
        prog=${PF_PROG}
    else
        prog=$(printf ${PROG_TEMPLATE} ${sx})
    fi

    # Prepare JSON conf
    if [[ -f ${USER_JSON_CONF} ]]; then
        # User config has precedence
        cp ${USER_JSON_CONF} ${JSON_CONF}
    else
        json_conf_template=$(printf ${JSON_CONF_TEMPLATE} ${sx} ${reg})
        prepare_conf_json ${json_conf_template} ${sx} ${reg} > ${JSON_CONF}
    fi

    # Must be run from the bin directory
    cd $(dirname ${PROG_TEMPLATE})
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${LIB_DIR}
    
    # stdbuf here forces line buffering, allowing real-time log
    stdbuf -oL -eL ${prog} &> ${LOG} &

    msg_done ${sx}/${reg}
}

stop() {
    msg_begin "Stopping packet-forwarder"

    test -s ${CONF} && source ${CONF}

    sx=$(find_sx)
    if [[ -n "${PF_PROG}" ]]; then
        prog=${PF_PROG}
    else
        prog=$(printf ${PROG_TEMPLATE} ${sx})
    fi
    base_prog=$(basename ${prog})
    if killall -q ${base_prog}; then
        # Allow 2 seconds for a gracefulish shutdown
        sleep 2
        msg_done
    else
        msg_fail
    fi

    # Kill any remainings with SIGKILL
    ps | grep '/opt/packet_forwarder' | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill -9
    ps | grep $(basename $0) | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill -9
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
