#!/bin/bash

PROG="/usr/libexec/print-pub-key-info"
USER_SWARM_KEY="/var/lib/user_swarm_key"
#PROV_REGISTER_URL="https://api-%s.syncrob.it/alienunit/"  # Use if service can't do region redirection
PROV_REGISTER_URL="https://api.syncrob.it/alienunit/"
AUTH_TOKEN="3F4ECC8F2C95134BCA7281C83B879"
REG_CONF="/var/lib/reg.conf"

source /etc/init.d/base

test -s ${REG_CONF} && source ${REG_CONF}
PROV_REGISTER_URL=$(printf "${PROV_REGISTER_URL}" "${REGION_PREFIX}")


send_prov_info() {
    test -r /sys/class/net/eth0/address && eth_mac=$(cat /sys/class/net/eth0/address)
    test -r /sys/class/net/wlan0/address && wlan_mac=$(cat /sys/class/net/wlan0/address)
    pub_key=$(cat /var/run/public_key_hex)
    hotspot_name=$(cat /var/run/hotspot_name)
    swarm_key_hex=$(cat ${USER_SWARM_KEY} 2>/dev/null | od -t x1 -w1000 -An | tr -d ' ')

    prov_info_json="{
        \"rpi_sn\":\"${BOARD_SN}\",
        \"pub_key\":\"${pub_key}\",
        \"eth_mac\":\"${eth_mac}\",
        \"wlan_mac\":\"${wlan_mac}\",
        \"swarm_key\":\"${swarm_key_hex}\",
        \"hotspot_name\":\"${hotspot_name}\"
    }"
    
    prov_info_json=$(echo "${prov_info_json}" | tr -d '\t\n ')
    
    curl --insecure --fail --silent --show-error --location-trusted "${PROV_REGISTER_URL}" \
         -H "Content-Type: application/json" \
         -H "Authorization: ${AUTH_TOKEN}" \
         -X POST -d "${prov_info_json}" >/dev/null
}

start() {
    msg_begin "Saving public key info"
    
    info=$(${PROG} ${USER_SWARM_KEY} || ${PROG} ${USER_SWARM_KEY} || ${PROG} ${USER_SWARM_KEY})
    info=(${info})
    ecc_sn=${info[0]}
    pub_key_hex=${info[1]}
    hotspot_name=$(cut -d '"' -f 6 < /var/run/public_keys)
    
    if [[ "${ecc_sn}" != "unknown" ]]; then
        echo "${ecc_sn}" > /var/run/ecc_sn
    else
        echo > /var/run/ecc_sn
    fi
    echo "${pub_key_hex}" > /var/run/public_key_hex
    echo "${hotspot_name}" > /var/run/hotspot_name

    msg_done

    if [[ -s ${USER_SWARM_KEY} ]]; then
        msg_begin "Sending provisioning info"
        send_prov_info &>/var/log/send-prov-info.log
        test $? == 0 && msg_done || msg_fail
    fi
}

case "$1" in
    start)
        start
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
