#!/bin/bash


MQTT_TOPIC="units/%s/logs/%s"

test -n "${OS_VERSION}" || source /etc/init.d/base

source /etc/mqtt-send.conf


send_log() {
    # $1 - content
    # $2 - topic
    # $3 - id
    mosquitto_pub -h ${MQTT_BROKER_HOST} -p ${MQTT_BROKER_PORT} -i "$3" -t "$2" -m "$1"
}

watch_file() {
    # $1 - file path
    # $2 - topic suffix
    id=$(hostname)
    topic=$(printf ${MQTT_TOPIC} ${id} $2)
    
    test -s $1 && send_log "$(cat $1)" "${topic}" "${id}"
    tail -n0 -qF "$1" 2>/dev/null | while read line; do send_log "${line}" "${topic}" "${id}"; done
}

start() {
    msg_begin "Starting log-sender"
    
    watch_file /var/log/packet_forwarder.log packet_forwarder &>>/var/log/send-logs.log &

    msg_done
}

stop() {
    msg_begin "Stopping log-sender"

    prog_name=$(basename $0)
    ps | grep ${prog_name} | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
