#!/bin/bash


PROG="/sbin/remote-api-server"
LOG="/var/log/remote-api-server.log"

source /etc/init.d/base


start() {
    msg_begin "Starting remote API server"
    
    ${PROG} &>${LOG} &

    msg_done
}

stop() {
    msg_begin "Stopping remote API server"

    prog_name=$(basename ${PROG})
    ps | grep ${prog_name} | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
