#!/bin/bash


source /etc/init.d/base
source /etc/mqtt-send.conf

MQTT_TOPIC_TEMPLATE="units/${OS_PREFIX}/${BOARD_SN}/logs/%s"
SEND_LOGS_ACTIVE="/var/run/send_logs_active"


send_log() {
    # $1 - content
    # $2 - topic
    # $3 - id
    
    test -e ${SEND_LOGS_ACTIVE} || return
    mosquitto_pub -h ${MQTT_BROKER_HOST} -p ${MQTT_BROKER_PORT} -i "$3" -t "$2" -u "${MQTT_BROKER_USERNAME}" -P "${MQTT_BROKER_PASSWORD}" -m "$1" ${MQTT_EXTRA_ARGS}
}

watch_file() {
    # $1 - file path
    # $2 - topic suffix
    file_path=$1
    topic=$(printf ${MQTT_TOPIC_TEMPLATE} $2)
    
    #test -s ${file_path} && send_log "$(cat ${file_path})" "${topic}" ${BOARD_SN}
    tail -n0 -qF "$1" 2>/dev/null | while read line; do send_log "${line}" "${topic}" ${BOARD_SN}; done
}

start() {
    msg_begin "Starting log-sender"
    
    watch_file /var/log/packet_forwarder.log packet_forwarder &>>/var/log/send-logs.log &
    watch_file /var/log/miner/console.log miner &>>/var/log/send-logs.log &

    msg_done
}

stop() {
    msg_begin "Stopping log-sender"

    prog_name=$(basename $0)
    ps | grep ${prog_name} | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
