#!/bin/bash

source /etc/init.d/base

#BASE_URL="https://fwd.%ssyncrob.it"  # Use if service can't do region redirection
BASE_URL="https://fwd.syncrob.it"
REG_CONF="/var/lib/reg.conf"
MIN_UPTIME=3600

test -s ${REG_CONF} && source ${REG_CONF}
BASE_URL=$(printf "${BASE_URL}" "${REGION_PREFIX}")

cmdline_args="$*"

function arg_present() {
    for arg in ${cmdline_args}; do
        if [ "${arg}" == "$1" ]; then
            return 0
        fi
    done

    return 1
}


echo "---- $(date) ----"

if [[ "${OS_DEBUG}" == "true" ]] && ! arg_present "--force"; then
    echo "Skipping firmware update check in debug mode"
    exit
fi

if ps aux | grep '{fwupdate}' | grep -vq grep && ! arg_present "--force"; then
    echo "Firmware update process is already running"
    exit
fi

uptime_seconds=$(cat /proc/uptime | grep -oE '^[[:digit:]]+')
if [[ ${uptime_seconds} -lt ${MIN_UPTIME} ]] && ! arg_present "--force"; then
    echo "Skipping firmware update check immediately after boot"
    exit
fi

if [[ "${OS_PRERELEASES}" == "true" ]]; then
    latest_file="latest.json"
else
    latest_file="latest_stable.json"
fi

latest_url="${BASE_URL}/cham/${latest_file}"
latest=$(curl -sSL ${latest_url})
latest=$(jq -r '.path,.version,.date' <<<"${latest}")
latest=(${latest})
latest_path=${latest[0]}
latest_version=${latest[1]}

if [[ "${OS_VERSION}" == "${latest_version}" ]]; then
    echo "Already running latest version (${latest_version})"
    exit
fi

firmware_url="${BASE_URL}${latest_path}"
panic_inhibit
echo "Updating from ${OS_VERSION} to ${latest_version} using ${firmware_url}"
fwupdate upgrade "${firmware_url}"
