#!/bin/bash

CREDENTIALS_FILE=/var/lib/api_credentials
DEF_CREDENTIALS="admin:admin"

credentials=${DEF_CREDENTIALS}
test -s ${CREDENTIALS_FILE} && credentials=$(cat ${CREDENTIALS_FILE})

echo "Testing network connection..."
curl -u "${credentials}" -s http://localhost/nettest?pretty=true | jq -r 'to_entries[] | (.key + ": " + (.value|tostring))' | sed 's/: /|/' | column -t -s '|'
