#!/bin/bash

SPEED_TEST_TIMEOUT=5  # Seconds
SPEED_TEST_URL=http://speedtest-blr1.digitalocean.com/10mb.test


function test_speed() {
    curl -o /dev/null --stderr /tmp/speedtest.txt -m ${SPEED_TEST_TIMEOUT} ${SPEED_TEST_URL}
    speed=$(cat /tmp/speedtest.txt | grep -v 'timed out' | tail -n 1 | tr -s ' ' | rev | cut -d ' ' -f 1 | rev | sed -r 's/([0-9]+)/\1 /')
    # Speed must start with a number
    [[ "${speed}" =~ ^[0-9] ]] || speed=0
    # Ensure speed is always expressed as kbytes/s
    speed=(${speed})
    if [[ ${#speed[@]} -gt 1 ]]; then
        unit=${speed[1]}
        speed=${speed[0]}
        if [[ ${unit} == M ]]; then
            speed=$(echo "${speed} * 1024" | bc -l)
        fi
    else  # Assuming no unit (bytes/s)
        speed=$(echo "${speed} / 1024" | bc -l)
    fi

    speed=$(printf "%.1f" ${speed})

    echo "Download speed: ${speed} kB/s"
}

function test_latency() {
    latency=$(ping -A -c 5 8.8.8.8 | tail -n 1 | cut -d '/' -f 4 | cut -d '.' -f 1)
    echo "Latency: ${latency} ms"
}

function test_public_ip() {
    ip=$(curl -s https://ipv4.icanhazip.com/)
    echo "Public IP: ${ip}"
}

echo "Testing network connection... "
test_speed
test_latency
test_public_ip
