#!/bin/bash


source /etc/init.d/base
source /etc/mqtt-send.conf

MQTT_TOPIC="units/${OS_PREFIX}/${BOARD_SN}/sys_info"


function prepare_payload() {
    cpu_usage=$(top -d1 -bn2 | grep '^CPU:' | tail -n1 | tr -s ' ' | cut -d ' ' -f 2,4 | tr -d '%' | tr ' ' + | bc)
    mem_info=($(free -m | grep '^Mem:' | tr -s ' ' | cut -d ' ' -f 2,3))
    storage_info=($(df -m /data | tail -n 1 | tr -s ' ' | cut -d ' ' -f 2,3))
    temperature=$(echo $(cat /sys/class/thermal/thermal_zone0/temp)/1000 | bc)
    latency=$(ping -w 2 -c 5 -A 1.1.1.1 | grep -oE '/[0-9.]+/' | tr -d '/' | grep -oE '^[0-9]+')
    test -n "${latency}" || latency=1000
    test "${latency}" -le 1000 || latency=1000

    # Don't bother miner while syncing
    if ps aux | grep snapshot | grep -qv grep; then
        miner_height="null"
        miner_listen_addr=""
    else
        miner_height=$(/opt/miner/bin/miner info height | tr '\t' ' ' | tr -s ' ' | cut -d ' ' -f 2 | grep -E '[[:digit:]]+')
        miner_listen_addr=$(/opt/miner/bin/miner peer book -s | grep "listen_addrs (prioritized)" -A2 | tail -n1 | tr -d '|')
    fi
    test -n "${miner_height}" || miner_height="null"
    system_uptime=$(cat /proc/uptime | grep -oE '^[[:digit:]]+')
    test -r /sys/class/net/eth0/address && eth_mac=$(cat /sys/class/net/eth0/address)
    test -r /sys/class/net/wlan0/address && wlan_mac=$(cat /sys/class/net/wlan0/address)
    address=$(cat /var/run/public_keys | grep -oE '[0-9a-zA-Z]{50,}' | head -n 1)
    pub_key=$(cat /var/run/public_key_hex)
    hotspot_name=$(cat /var/run/hotspot_name)
    test -r /var/lib/reg.conf && source /var/lib/reg.conf
    swarm_key_mode=$(test -s /var/lib/user_swarm_key && echo true || echo false)
    time=$(date +%s)
    concentrator_model=$(ps aux | grep /opt/packet_forwarder/bin/lora_pkt_fwd_ | grep -oE 'sx13.*' 2>/dev/null)
    if [[ -s /var/lib/last_panic ]]; then
        source /var/lib/last_panic
        last_panic="{
            \"service\":\"${service}\",
            \"message\":\"${message}\",
            \"timestamp\":${timestamp},
            \"uptime\":${uptime}
        }"
    else
        last_panic=null
    fi
    
    if [[ -s /var/run/led_state ]]; then
        current_state=$(cat /var/run/led_state)
    else
        current_state=powered_up
    fi

    payload="{
        \"cpu_usage\":${cpu_usage},
        \"mem_used\":${mem_info[1]},
        \"mem_total\":${mem_info[0]},
        \"storage_used\":${storage_info[1]},
        \"storage_total\":${storage_info[0]},
        \"temperature\":${temperature},
        \"latency\":${latency},
        \"miner_height\":${miner_height},
        \"miner_listen_address\":\"${miner_listen_addr}\",
        \"hotspot_name\":\"${hotspot_name}\",
        \"concentrator_model\":\"${concentrator_model}\",
        \"region\":\"${REGION}\",
        \"fw_version\":\"${OS_VERSION}\",
        \"swarm_key_mode\":${swarm_key_mode},
        \"address\":\"${address}\",
        \"pub_key\":\"${pub_key}\",
        \"eth_mac\":\"${eth_mac}\",
        \"wlan_mac\":\"${wlan_mac}\",
        \"uptime\":${system_uptime},
        \"time\":${time},
        \"last_panic\":${last_panic},
        \"current_state\":\"${current_state}\"
    }"

    payload=$(echo ${payload} | jq -c)
    echo "${payload}"
}

echo "---- $(date) ----"
if ! [[ -f /var/run/hotspot_name ]]; then
    echo "miner not started yet"
    exit 0
fi

if ps aux | grep '{send-sys-info}' | grep -v $$ | grep -vq grep; then
    echo "another instance already running"
    exit 0
fi

echo "preparing payload"
payload=$(prepare_payload)
echo "sending MQTT message"
mosquitto_pub -h ${MQTT_BROKER_HOST} -p ${MQTT_BROKER_PORT} -t ${MQTT_TOPIC} -u "${MQTT_BROKER_USERNAME}" -P "${MQTT_BROKER_PASSWORD}" -m "${payload}" -i ${BOARD_SN} ${MQTT_EXTRA_ARGS}
echo "done"
