#!/bin/bash

source /etc/init.d/base

BASE_URL="http://firmware.syncrob.it"
MIN_UPTIME=600


if ps aux | grep fwupdate | grep -v $$ |grep -vq grep; then
    echo "Firmware update process is already running"
    exit
fi

uptime_seconds=$(cat /proc/uptime | grep -oE '^[[:digit:]]+')
if [[ ${uptime_seconds} -lt ${MIN_UPTIME} ]]; then
    echo "Skipping firmware update check immediately after boot"
    exit
fi

if [[ "${OS_PRERELEASES}" == "true" ]]; then
    latest_file="latest.json"
else
    latest_file="latest_stable.json"
fi

latest_url="${BASE_URL}/${latest_file}"
latest=$(curl -sSL ${latest_url})
latest=$(jq -r '.path,.version,.date' <<<"${latest}")
latest=(${latest})
latest_path=${latest[0]}
latest_version=${latest[1]}

if [[ "${OS_VERSION}" == "${latest_version}" ]]; then
    echo "Already running latest version (${latest_version})"
    exit
fi

firmware_url="${BASE_URL}${latest_path}"
touch /var/run/panic_prohibited
echo "Updating from ${OS_VERSION} to ${latest_version} using ${firmware_url}"
fwupdate upgrade "${firmware_url}"
