#!/bin/bash

ONLINE=$1
#API_ENDPOINT_URL="https://api.%ssyncrob.it/advertise/"  # Use if service can't do region redirection
API_ENDPOINT_URL="https://api.syncrob.it/advertise/"
AUTH_TOKEN="3F4ECC8F2C95134BCA7281C83B879"
REG_CONF="/var/lib/reg.conf"

test -n "${OS_VERSION}" || source /etc/init.d/base
test -s ${REG_CONF} && source ${REG_CONF}
API_ENDPOINT_URL=$(printf "${API_ENDPOINT_URL}" "${REGION_PREFIX}")

is_public_ip() {
    addr=$1

    test -n "${addr}" || return 1

    if [[ "${addr}" =~ ^10\. ]]; then
        return 1
    elif [[ "${addr}" =~ ^172\. ]]; then  # Not really RFC1918!
        return 1
    elif [[ "${addr}" =~ ^192\.168\. ]]; then
        return 1
    fi
}

if [[ "${ONLINE}" == true ]]; then
    addr_wlan0=$(ip addr show dev wlan0 2>/dev/null | grep 'inet ' | tr -s ' ' | sed -r 's/^\s+//' | \
                 cut -d ' ' -f 2 | sed 'N;s/\n/, /' | head -n1)
    addr_eth0=$(ip addr show dev eth0 2>/dev/null | grep 'inet ' | tr -s ' ' | sed -r 's/^\s+//' | \
                cut -d ' ' -f 2 | sed 'N;s/\n/, /' | head -n1)
    addr_tun0=$(ip addr show dev tun0 2>/dev/null | grep 'inet ' | tr -s ' ' | sed -r 's/^\s+//' | \
                cut -d ' ' -f 2 | sed 'N;s/\n/, /' | head -n1)

    test -n "${addr_wlan0}" && addr=${addr_wlan0} || addr=${addr_eth0}
    
    # Block HTTP traffic if on public IP
    if is_public_ip "${addr}"; then
        if ! iptables -C INPUT -i eth0 -p tcp --dport 80 -j DROP &>/dev/null; then
            msg_begin "Blocking HTTP traffic"
            iptables -A INPUT -i eth0 -p tcp --dport 80 -j DROP
            iptables -A INPUT -i wlan0 -p tcp --dport 80 -j DROP
            msg_done
        fi
    fi

    msg_begin "Sending local IP address \"${addr}\", VPN IP address \"${addr_tun0}\""

    payload="{
        \"rpi_sn\":\"${BOARD_SN}\",
        \"hostname\":\"$(hostname)\",
        \"ip_addr_local\":\"${addr}\",
        \"ip_addr_vpn\":\"${addr_tun0}\"
    }"

    curl --fail --insecure --silent --show-error --location-trusted "${API_ENDPOINT_URL}" \
         -H "Content-Type: application/json" \
         -H "Authorization: ${AUTH_TOKEN}" \
         -X POST -d "${payload}" >/dev/null

    if [[ $? == 0 ]]; then
        msg_done
    else
        msg_fail
        exit 1
    fi
fi
